language: python
cache: pip
python:
    - 2.7
install:
    - pip install -r requirements.txt
    - python setup.py build_ext --inplace
    - python setup.py develop
script:
    - pip install "pytest>=3"
    - py.test -k 'not mdf/tests/test_remote.py' mdf/tests
    - py.test mdf/tests/test_remote.py
