language: python
python:
    - 2.7
install:
    - pip install -r requirements.txt
    - python setup.py build_ext --inplace
    - python setup.py develop
script: py.test -k 'not test_multiprocess_run' mdf/tests
