{% set version = "2.2.1" %}

package:
  name: mdf
  version: {{ version }}

source:
  git_url: https://github.com/florin-court/mdf.git
  git_rev: {{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - cython <0.23
    - numpy
    - pyzmq
    - pyro4 4.14
    - decorator
    - pandas
    - pyparsing
    - matplotlib
    - xlwt
    - pydot

  run:
    - python
    - numpy
    - pyzmq
    - pyro4 4.14
    - decorator
    - pandas
    - pyparsing
    - matplotlib
    - xlwt
    - pydot

test:
  imports:
    - mdf

about:
  home: https://github.com/ddunwoody/mdf
  license: MIT
  summary: Data-flow programming toolkit for Python

extra:
  recipe-maintainers:
    - ddunwoody
